Repository peerplays-network/peerplays, pull requests merged in 2019-09, with the labels that each got.

#98 Cli wallet tests framework
  libraries/wallet/wallet.cpp
  tests/CMakeLists.txt
  tests/cli/main.cpp
Labels: enhancement

#89 GRPH-4-CliWallet_crash_ctrlD
  libraries/app/application.cpp
  libraries/plugins/delayed_node/delayed_node_plugin.cpp
  programs/cli_wallet/main.cpp
Labels: bug

#70 [GRPH-59] Proposal failure handling
  CMakeLists.txt
  libraries/chain/include/graphene/chain/proposal_object.hpp
  libraries/chain/include/graphene/chain/vesting_balance_object.hpp
  libraries/chain/proposal_evaluator.cpp
  libraries/chain/proposal_object.cpp
  tests/tests/authority_tests.cpp
Labels: bug

#60 Grph 48 object database 18.04
  libraries/app/database_api.cpp
  libraries/db/include/graphene/db/index.hpp
Labels: Changes Requested

#69 [GRPH-49] get_account_history fix
  libraries/app/api.cpp
  tests/tests/history_api_tests.cpp
Labels: Changes Requested

#117 GRPH-90 Fix for history ID mismatch issue
  libraries/app/api.cpp
  libraries/plugins/account_history/account_history_plugin.cpp
  tests/common/database_fixture.cpp
  tests/tests/history_api_tests.cpp
Labels: ready2merge

#123 Support/gitlab
  .gitlab-ci.yml
Labels: build

#110 [GRPH-73] fix block id forks
  libraries/chain/db_block.cpp
  tests/tests/block_tests.cpp
Labels: fork-handling

#95 issue - 157: Don't allow to vote when the vesting balance is 0
  libraries/wallet/wallet.cpp
Labels: enhancement
