Repository peerplays-network/peerplays, pull requests merged in 2019-10, with the labels that each got.

#159 Added code_quality to CI
  .gitlab-ci.yml
Labels: merged

#164 163-fix, Return only non-zero vesting balances
  libraries/app/database_api.cpp
Labels: ready2merge

#163 Changes to have separate withdraw_vesting methods and single withdraw fee for multiple objects
  libraries/chain/include/graphene/chain/vesting_balance_evaluator.hpp
  libraries/chain/vesting_balance_evaluator.cpp
  libraries/wallet/include/graphene/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
Labels: ready2merge

#146 [GRPH-112] Doxyfile updates
  Doxyfile
Labels: Changes Requested

#179 [SON-113] Unit test for cli `update_son_votes`
  libraries/wallet/include/graphene/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  programs/build_helpers/cat-parts
  tests/cli/cli_fixture.cpp
  tests/cli/cli_fixture.hpp
  tests/cli/main.cpp
  tests/cli/son.cpp
Labels: merged

#192 SON126 - Witness Proposals to deregister SONs
  libraries/chain/db_block.cpp
  libraries/chain/db_getter.cpp
  libraries/chain/db_init.cpp
  libraries/chain/include/graphene/chain/config.hpp
  libraries/chain/include/graphene/chain/database.hpp
  libraries/chain/include/graphene/chain/proposal_evaluator.hpp
  libraries/chain/include/graphene/chain/protocol/son.hpp
  libraries/chain/include/graphene/chain/protocol/types.hpp
  libraries/chain/include/graphene/chain/son_object.hpp
  libraries/chain/include/graphene/chain/son_proposal_object.hpp
  libraries/chain/proposal_evaluator.cpp
  libraries/chain/son_evaluator.cpp
  libraries/wallet/wallet.cpp
  tests/tests/son_operations_tests.cpp
Labels: merged
