Repository peerplays-network/peerplays, pull requests merged in 2019-12, with the labels that each got.

#90 GRPH-46-Quit_command_cliwallet
  libraries/wallet/include/graphene/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
Labels: enhancement

#243 [BLOCKBACK-186] Withdraw vesting bug fix
  libraries/chain/vesting_balance_evaluator.cpp
  tests/tests/gpos_tests.cpp
Labels: bug, hardfork, merged

#251 SON207 - Introduce scheduling for SONs similar to witnesses
  libraries/chain/db_block.cpp
  libraries/chain/db_init.cpp
  libraries/chain/db_maint.cpp
  libraries/chain/db_witness_schedule.cpp
  libraries/chain/include/graphene/chain/database.hpp
  libraries/chain/include/graphene/chain/protocol/types.hpp
  libraries/chain/include/graphene/chain/witness_schedule_object.hpp
Labels: merged

#253 GPOS-1, Testnet sync issue fix
  libraries/chain/include/graphene/chain/protocol/vesting.hpp
  libraries/chain/vesting_balance_evaluator.cpp
  libraries/wallet/wallet.cpp
  tests/tests/gpos_tests.cpp
Labels: hardfork
